### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez1294** [GabrielHaurane/Frontend-Proyecto-Final#19]
Esperado: Que se encuentre el logo junto con el nombre.
Actual: No se encuentra el logo
![image](https://github.com/user-attachments/assets/8b38167f-82b7-46e4-ba88-5cdca57073dd)
Cualquier cosita pueden contactarme por el slack de RollingCode

**Comment by GabrielHaurane** [comment]
ahi se cambio el favicon
