### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by NicoGonzalez1294** [GabrielHaurane/Frontend-Proyecto-Final#20]
Esperado: Encontrar mas contenido en el footer (Ej: Redes sociales,).
![image](https://github.com/user-attachments/assets/a6086229-fdc9-4ef0-bb41-7b48c67d3166)
Cualquier cosita pueden contactarme por el slack de RollingCode

**Comment by GabrielHaurane** [comment]
ahi se agrego redes sociales y Copyright
